FROM alpine:3.23

ENV PHP_VERS=84

# upgrade system / install apache
RUN apk upgrade --no-cache \
        && apk add --no-cache \
        apache2 apache2-brotli apache2-utils apache2-proxy doas \
        s6 setpriv \
        # cleanup, do not use default apache configuration files but preserve them as examples
        && for x in /etc/apache2/conf.d/*.conf; do mv $x $x.bak; done \
        # disable mpm_prefork module, we use mpm_event
        && sed -i 's/^LoadModule mpm_prefork_module/#LoadModule mpm_prefork_module/' /etc/apache2/httpd.conf \
        # disable document root, we define it in the vhost.conf
        && sed -i 's/^DocumentRoot/#DocumentRoot/' /etc/apache2/httpd.conf \
        # we will run with our custom structure under /var/www/, cleanup existing files
        && rm -rf /var/www \
        # configure doas for cron
        && echo 'permit nopass app as root cmd /usr/sbin/crond' >>/etc/doas.d/doas.conf

# install php with modules
RUN apk add --no-cache \
        php${PHP_VERS}-cli \
        php${PHP_VERS}-fpm \
        php${PHP_VERS}-ctype \
        php${PHP_VERS}-curl \
        php${PHP_VERS}-exif \
        php${PHP_VERS}-fileinfo \
        php${PHP_VERS}-gd \
        php${PHP_VERS}-gmp \
        php${PHP_VERS}-iconv \
        php${PHP_VERS}-imap \
        php${PHP_VERS}-intl \
        php${PHP_VERS}-json \
        php${PHP_VERS}-mbstring \
        php${PHP_VERS}-mysqli \
        php${PHP_VERS}-mysqlnd \
        php${PHP_VERS}-pgsql \
        php${PHP_VERS}-opcache \
        php${PHP_VERS}-openssl \
        php${PHP_VERS}-pecl-apcu \
        php${PHP_VERS}-pecl-imagick \
        php${PHP_VERS}-pdo_mysql \
        php${PHP_VERS}-pdo_pgsql \
        php${PHP_VERS}-simplexml \
        php${PHP_VERS}-session \
        php${PHP_VERS}-soap \
        php${PHP_VERS}-sqlite3 \
        php${PHP_VERS}-xml \
        php${PHP_VERS}-xmlreader \
        php${PHP_VERS}-zip \
        php${PHP_VERS}-zlib \
    && rm -v /etc/php${PHP_VERS}/php-fpm.d/*

# add the custom configurations
COPY rootfs/ /

VOLUME /var/www/htdocs
VOLUME /var/www/logs
VOLUME /var/www/tmp

# server defaults to port 80
EXPOSE 8080

CMD [ "/entrypoint.sh" ]

# vim: set filetype=dockerfile:
