FROM alpine:3.16

# upgrade system / install apache
RUN apk upgrade --no-cache \
        && apk add --no-cache \
        apache2 apache2-brotli apache2-utils apache2-proxy doas \
        s6 setpriv \
        # cleanup, do not use default apache configuration files but preserve them as examples
        && for x in /etc/apache2/conf.d/*.conf; do mv $x $x.bak; done \
        # disable mpm_prefork module, we use mpm_event
        && sed -i 's/^LoadModule mpm_prefork_module/#LoadModule mpm_prefork_module/' /etc/apache2/httpd.conf \
        # disable document root, we define it in the vhost.conf
        && sed -i 's/^DocumentRoot/#DocumentRoot/' /etc/apache2/httpd.conf \
        # we will run with our custom structure under /var/www/, cleanup existing files
        && rm -rf /var/www \
        # configure doas for cron
        && echo 'permit nopass app as root cmd /usr/sbin/crond' >>/etc/doas.d/doas.conf

# install php with modules
RUN apk add --no-cache -X https://dl-cdn.alpinelinux.org/alpine/edge/testing \
        php81-cli \
        php81-fpm \
        php81-ctype \
        php81-curl \
        php81-exif \
        php81-fileinfo \
        php81-gd \
        php81-gmp \
        php81-iconv \
        php81-imap \
        php81-intl \
        php81-json \
        php81-mbstring \
        php81-mysqli \
        php81-mysqlnd \
        php81-pgsql \
        php81-opcache \
        php81-openssl \
        php81-pecl-imagick \
        php81-pecl-mcrypt \
        php81-pdo_mysql \
        php81-pdo_pgsql \
        php81-simplexml \
        php81-session \
        php81-soap \
        php81-sqlite3 \
        php81-xml \
        php81-xmlreader \
        php81-zip \
        php81-zlib \
    && (if [ -d /etc/php*/php-fpm.d/ ]; then rm -v /etc/php*/php-fpm.d/*; fi)

# add the custom configurations
COPY rootfs/ /

VOLUME /var/www/htdocs
VOLUME /var/www/logs
VOLUME /var/www/tmp

# server defaults to port 80
EXPOSE 8080

CMD [ "/entrypoint.sh" ]
