FROM alpine:3.16

# upgrade system / install apache
RUN apk upgrade --no-cache \
        && apk add --no-cache \
        apache2 apache2-brotli apache2-utils apache2-proxy doas \
        s6 setpriv \
        # cleanup, do not use default apache configuration files but preserve them as examples
        && for x in /etc/apache2/conf.d/*.conf; do mv $x $x.bak; done \
        # disable mpm_prefork module, we use mpm_event
        && sed -i 's/^LoadModule mpm_prefork_module/#LoadModule mpm_prefork_module/' /etc/apache2/httpd.conf \
        # disable document root, we define it in the vhost.conf
        && sed -i 's/^DocumentRoot/#DocumentRoot/' /etc/apache2/httpd.conf \
        # we will run with our custom structure under /var/www/, cleanup existing files
        && rm -rf /var/www \
        # configure doas for cron
        && echo 'permit nopass app as root cmd /usr/sbin/crond' >>/etc/doas.d/doas.conf

# install php with modules
RUN apk add --no-cache \
        php8-cli \
        php8-fpm \
        php8-ctype \
        php8-curl \
        php8-exif \
        php8-fileinfo \
        php8-gd \
        php8-gmp \
        php8-iconv \
        php8-imap \
        php8-intl \
        php8-json \
        php8-mbstring \
        php8-mysqli \
        php8-mysqlnd \
        php8-pgsql \
        php8-opcache \
        php8-openssl \
        php8-pecl-imagick \
        php8-pecl-mcrypt \
        php8-pdo_mysql \
        php8-pdo_pgsql \
        php8-simplexml \
        php8-session \
        php8-soap \
        php8-sqlite3 \
        php8-xml \
        php8-xmlreader \
        php8-zip \
        php8-zlib \
    && (if [ -d /etc/php?/php-fpm.d/ ]; then rm -v /etc/php?/php-fpm.d/*; fi)

# add the custom configurations
COPY rootfs/ /

VOLUME /var/www/htdocs
VOLUME /var/www/logs
VOLUME /var/www/tmp

# server defaults to port 80
EXPOSE 8080

CMD [ "/entrypoint.sh" ]
