FROM alpine:3.8

# upgrade system / install apache
RUN apk upgrade --no-cache \
        && apk add --no-cache \
        apache2 apache2-utils apache2-proxy sudo \
        s6 setpriv \
        # cleanup, do not use default apache configuration files but preserve them as examples
        && for x in /etc/apache2/conf.d/*.conf; do mv $x $x.bak; done \
        # disable mpm_prefork module, we use mpm_event
        && sed -i 's/^LoadModule mpm_prefork_module/#LoadModule mpm_prefork_module/' /etc/apache2/httpd.conf \
        # disable document root, we define it in the vhost.conf
        && sed -i 's/^DocumentRoot/#DocumentRoot/' /etc/apache2/httpd.conf \
        # we will run with our custom structure under /var/www/, cleanup existing files
        && rm -rf /var/www \
        # configure sudo for cron
	&& echo 'app ALL=NOPASSWD: /usr/sbin/crond' >>/etc/sudoers

# install php with modules
RUN apk add --no-cache \
        php5-cli \
        php5-fpm \
        php5-ctype \
        php5-curl \
        php5-exif \
        php5-gd \
        php5-gmp \
        php5-iconv \
        php5-imap \
        php5-intl \
        php5-json \
        php5-mcrypt \
        php5-mysqli \
        php5-pgsql \
        php5-opcache \
        php5-openssl \
        php5-pdo_mysql \
        php5-pdo_pgsql \
        php5-soap \
        php5-sqlite3 \
        php5-xml \
        php5-xmlreader \
        php5-zip \
        php5-zlib \
    && (if [ -d /etc/php?/php-fpm.d/ ]; then rm -v /etc/php?/php-fpm.d/*; fi)

# add the custom configurations
COPY rootfs/ /

VOLUME /var/www/htdocs
VOLUME /var/www/logs
VOLUME /var/www/tmp

# server defaults to port 80
EXPOSE 8080

CMD [ "/entrypoint.sh" ]
