FROM alpine:3.18

# upgrade system / install apache
RUN apk upgrade --no-cache \
        && apk add --no-cache \
        apache2 apache2-brotli apache2-utils apache2-proxy doas \
        s6 setpriv \
        # cleanup, do not use default apache configuration files but preserve them as examples
        && for x in /etc/apache2/conf.d/*.conf; do mv $x $x.bak; done \
        # disable mpm_prefork module, we use mpm_event
        && sed -i 's/^LoadModule mpm_prefork_module/#LoadModule mpm_prefork_module/' /etc/apache2/httpd.conf \
        # disable document root, we define it in the vhost.conf
        && sed -i 's/^DocumentRoot/#DocumentRoot/' /etc/apache2/httpd.conf \
        # we will run with our custom structure under /var/www/, cleanup existing files
        && rm -rf /var/www \
        # configure doas for cron
        && echo 'permit nopass app as root cmd /usr/sbin/crond' >>/etc/doas.d/doas.conf

# install php with modules
RUN apk add --no-cache -X https://dl-cdn.alpinelinux.org/alpine/edge/testing \
        php82-cli \
        php82-fpm \
        php82-ctype \
        php82-curl \
        php82-exif \
        php82-fileinfo \
        php82-gd \
        php82-gmp \
        php82-iconv \
        php82-imap \
        php82-intl \
        php82-json \
        php82-mbstring \
        php82-mysqli \
        php82-mysqlnd \
        php82-pgsql \
        php82-opcache \
        php82-openssl \
        php82-pecl-imagick \
        php82-pecl-mcrypt \
        php82-pdo_mysql \
        php82-pdo_pgsql \
        php82-simplexml \
        php82-session \
        php82-soap \
        php82-sqlite3 \
        php82-xml \
        php82-xmlreader \
        php82-zip \
        php82-zlib \
    && (if [ -d /etc/php*/php-fpm.d/ ]; then rm -v /etc/php*/php-fpm.d/*; fi)

# add the custom configurations
COPY rootfs/ /

VOLUME /var/www/htdocs
VOLUME /var/www/logs
VOLUME /var/www/tmp

# server defaults to port 80
EXPOSE 8080

CMD [ "/entrypoint.sh" ]
