FROM alpine:3.9

# upgrade system / install apache
RUN apk upgrade --no-cache \
        && apk add --no-cache \
        apache2 apache2-utils apache2-proxy doas \
        s6 setpriv \
        # cleanup, do not use default apache configuration files but preserve them as examples
        && for x in /etc/apache2/conf.d/*.conf; do mv $x $x.bak; done \
        # disable mpm_prefork module, we use mpm_event
        && sed -i 's/^LoadModule mpm_prefork_module/#LoadModule mpm_prefork_module/' /etc/apache2/httpd.conf \
        # disable document root, we define it in the vhost.conf
        && sed -i 's/^DocumentRoot/#DocumentRoot/' /etc/apache2/httpd.conf \
        # we will run with our custom structure under /var/www/, cleanup existing files
        && rm -rf /var/www \
        # configure doas for cron
        && echo 'permit nopass app as root cmd /usr/sbin/crond' >>/etc/doas.conf

# install php with modules
RUN apk add --no-cache \
        php7-cli \
        php7-fpm \
        php7-ctype \
        php7-curl \
        php7-exif \
        php7-fileinfo \
        php7-gd \
        php7-gmp \
        php7-iconv \
        php7-imap \
        php7-intl \
        php7-json \
        php7-mbstring \
        php7-mcrypt \
        php7-mysqli \
        php7-mysqlnd \
        php7-pgsql \
        php7-opcache \
        php7-openssl \
        php7-pecl-imagick \
        php7-pdo_mysql \
        php7-pdo_pgsql \
        php7-simplexml \
        php7-session \
        php7-soap \
        php7-sqlite3 \
        php7-xml \
        php7-xmlreader \
        php7-zip \
        php7-zlib \
    && (if [ -d /etc/php?/php-fpm.d/ ]; then rm -v /etc/php?/php-fpm.d/*; fi)

# add the custom configurations
COPY rootfs/ /

VOLUME /var/www/htdocs
VOLUME /var/www/logs
VOLUME /var/www/tmp

# server defaults to port 80
EXPOSE 8080

CMD [ "/entrypoint.sh" ]
